services:
  sqledge:
    # Image details
    image: mcr.microsoft.com/azure-sql-edge:latest
    # Docker container name
    container_name: db-msazureedgesql
    # Docker container behaviour
    restart: unless-stopped
    # DB port mapping
    ports:
      - "1433:1433"
    environment:
      # Accept EULA Flag
      ACCEPT_EULA: "Y"
      # User
      MSSQL_USER: SA
      # Set strong SA password
      MSSQL_SA_PASSWORD: B1gStrongPassw0rd
      # Use Developer or Edge license
      MSSQL_PID: "Developer"
      # Enable SQLServer Agent to handle T-SQL jobs
      MSSQL_AGENT_ENABLED: "TRUE"
      # DB Collation
      MSSQL_COLLATION: "SQL_Latin1_General_CP1_CI_AS"
    volumes:
      - ../db:/var/opt/mssql
    # Platform may vary based on your device
    platform: linux/arm64
    deploy:
      resources:
        # Usage limits in terms of vCpu and RAM
        limits:
          cpus: '1.0'
          memory: 2G